import Header from './components/Header'
import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Insights blog',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en" data-theme="forest">
      <body className="bg-[#071422]">
        <Header/>
        {children}
      </body>
    </html>
  )
}
