"use client";
import Header from './components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { useState} from 'react'

export const metadata: Metadata = {
  title: 'Insights blog',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  const [theme, setTheme] = useState("forest");

  return (
    <html lang="en" data-theme={theme}>
      <body className="relative bg-[#071422]">
        <Header/>
        {children}
      </body>
    </html>
  )
}
